# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Workerpedia"
license = "MIT"
licenselink = "https://github.com/the-idc/hugo-theme-workerpedia/blob/master/LICENSE.md"
description = "Documentation theme for Hugo, based on Learn theme"
homepage = "https://github.com/the-idc/hugo-theme-workerpedia/"
repo = "https://github.com/matcornic/hugo-theme-workerpedia"
tags = ["organizing"]
features = ["search"]
min_version = 0.25

[author]
  name = "IDC"
  homepage = "https://joinidc.co"

[original]
  name = "Mathieu Cornic"
  homepage = "https://learn.netlify.app/"
  repo = "https://github.com/getgrav/grav-learn"
